### ISSUE TITLE
shell key in schema

### ISSUE THREAD

**Issue by shahzebsiddiqui** [HPC-buildtest/schemas#10]
@vsoch 

Inspired by GitHub action https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell i think the `shell` key would be useful if we change its behavior. Let's face it, our current implementation of having `shell` can be achieved with using `run` key so I'd propose we change the behavior of `shell` key to mimic the GitHub action. Not all the features but some of it. The default shell can be `bash` but it can be changed
 
The script below will run in `bash` shell it is assumed `shell: bash`  and key is not required.

```
version: 0.0.1
shell_check:
  type: script
  run: |
    echo $SHELL
```

This allows user to write test in any shell so for instance they can write a test for `csh` as follows

```
version: 0.0.1
shell_check:
  type: script
  shell: csh
  run: |
    echo $SHELL
    setenv PATH $PATH:\/home/user/bin
    printenv  
```

Next we can extend the `run` key to accept python code if `shell: python` so it makes it easy to write scripts. Setting `shell: python` will use the python interpreter.

```
version: 0.0.1
shell_check:
  type: script
  shell: python
  run: |
    import os
    print os.cwd    
```

We can decide for python interpreter to either default to the following

1.  /usr/bin/python
2. python wrapper in $PATH

If we decide with **1.** then we can avoid unexpected results with user environment (virtualenv, conda, pip, module) that can affect python wrapper when running buildtest. If we go with **1.** then we are writing in Python 2 assuming ``/usr/bin/python`` exist in the system. If it doesn't it should through an error which is fine, because we expect same behavior if a shell is not available lets say ``/bin/csh`` is not available then ``shell: csh`` should error out.

If we go with **1.** then we may need ``shell: python3`` to accept python 3 script in this case ``/usr/bin/python3``. 

If we go with **2.** then we don't have to worry about system python but it can cause confusion to user if it is accepting python 2 or python 3. 

For now i think it is sufficient to allow the follow values

``shell: bash``, ``shell: csh``, ``shell: sh``, ``shell: python``, ``shell: python3``

**Comment by vsoch** [comment]
Agree. I'll make some time to put in these changes.

**Comment by vsoch** [comment]
If we are allowing any executable, why should we limit to that set? Why not allow an executable, find the first on the path, and go from there? If we start with a limited subset, it's almost certain that someone will come along and request another one. Is this for security? For example, if I want to run my tests using a conda environment, there will likely be some specification to activate it, and then I wouldn't want `/usr/bin/python`. I think we should have a default, but limit the restriction until we have a strong use case to enforce it.

**Comment by vsoch** [comment]
For GitHub actions, the reason I believe they have this is because they are completely controlling the environment, and the assumption is that if a user wants a custom executable he/she will use bash or sh. In our case, the user is controlling the environment, and heck, might want to use some niche interpreter.
