### ISSUE TITLE
Tests needed for a schema

### ISSUE THREAD

**Issue by vsoch** [HPC-buildtest/schemas#2]
It should conform to whatever format we decide to use (need to research this a bit and see what other groups use). Since buildtest is strongly yaml, I'm thinking we should maintain that.

**Comment by vsoch** [comment]
Updating with more knowledge now! We will need to:

 - For each schema, test it against it's versioned example (this means we should create an updated example when a schema is updated, and the CI should fail if it doesn't find it. 
 - For each schema, ensure that the naming / organization is consistent. E.g., it should be like `<name>-v<version>.schema.json` and organized in the folder with the same `<name>`. The examples should follow accordingly in an examples folder as a subfolder, e.g., so for this first PR we will have:

```
schemas/
    script/
        script-v0.0.1.schema.json
        examples/
            script-v0.0.1.yml
```
And we can more cleanly put multiple different things to test in each yml, but if absolutely necessary, we could also allow any prefix between 0.0.1 and yml, e.g.,

```
schemas/
    script/
        script-v0.0.1.schema.json
        examples/
            script-v0.0.1-bash.yml
            script-v0.0.1-hello-world.yml
```
As another option, we could organize based on version:

```
schemas/
    script/
        script-v0.0.1.schema.json
        examples/
            v0.1.0/
                bash.yml
                hello-world.yml
```
That is a little easier on the eyes, plus the version is also kept in the recipe header itself. Thoughts?

**Comment by shahzebsiddiqui** [comment]
I like the naming scheme ``script-v0.0.1.schema.json``, but question is it necessary to have **schema.json** at end of file. Considering that we store all schema files under a top level directory **schema** and we know that all schema will be **.json** files maybe we can simplify this a bit as follows

```
schemas/
    script/
        script-v0.0.1.json
        examples/
            v0.1.0/
                bash.yml
                hello-world.yml
```

**Comment by vsoch** [comment]
It's being treated as an extension, because you can imagine a case of having multiple schemas _and_ unrelated json files in a folder - we can identify the schemas with `schema.json`. This is also something that I've seen in the wild, so I think it makes sense. Without that extension, I have no good way of knowing what `script-v0.0.1.json` out of the context of being in a folder.

**Comment by shahzebsiddiqui** [comment]
I get your point. I didn't think of that, yea there can certainly be some input files (json) as part of  some test  and  now it makes sense to differentiate schema files from input files. I am +1 for `.schema.json` as an extension.

**Comment by vsoch** [comment]
This is all set! We have an organization and testing framework set up, so closing issue. If we want to further/change development after I add schemas to buildtest then we can open another issue.
