### ISSUE TITLE
Decide on yaml validator

### ISSUE THREAD

**Issue by vsoch** [HPC-buildtest/schemas#3]
I'm thinking we should stay in python, and only include possibly one extra dependency that already uses libraries already used by builtest. Here are some choices:

 - https://github.com/23andMe/Yamale: I like this one because it seems fairly used, and it lets us write the specifications (schemas) to look like the yaml files they will be validating. The "include" is also very nice, since we have shared metadata sometimes.
 - https://github.com/pyeve/cerberus seems nice, but I think we would need to maintain the schemas in json. It would always mean reading in the yaml file to a dictionary before validation, and we'd have to be assured that the translation from yaml -> json would hold the same structure, generally.
 - json-schema https://json-schema-everywhere.github.io/yaml is a fairly well established library that we could also use, as it can be used for yaml! Again, we would need to store the schemas in json, and they would validate yaml. This is something I'm open to because it looks like [opencontainers](https://github.com/opencontainers/image-spec/blob/master/schema/config-schema.json) uses this for their manifests. 
 - python-jsonschema seems like a similar initiative, although I don't see an advertisement about being intended for parsing yaml too. [Here is an example](https://python-jsonschema.readthedocs.io/en/stable/validate/) [here is the repo](https://github.com/Julian/jsonschema).

@shahzebsiddiqui what are your thoughts? I can start writing out the proposals for the schemas once we choose a library for the validation that we like, then we can discuss those details, and after it looks good I'll add functions to buildtest to interact with. I'll push a README with some early details in a few minutes.

**Comment by shahzebsiddiqui** [comment]
YaMale 
----------

**Pros:**
- Tested for Python 3.6 according to Travis: https://travis-ci.org/23andMe/Yamale but document says 3.4
- Schema written in YAML very simple to use with very advanced concept such as recursion 

**Cons:**
- Small community 
- 19 contributors 
- Started in 2014
- No slack channel

Cerebus
-----------

Released in 2013 about 50 contributors
Tested for Python 3.6, 3.7, 3.8 according to Travis: https://travis-ci.org/pyeve/cerberus
**Pros**

- Able to validate YAML file by converting YAML to json
- Supports recursion of data objects
- ``check_with`` is an interesting feature https://docs.python-cerberus.org/en/stable/validation-rules.html#check-with
- dependencies is a very useful feature https://docs.python-cerberus.org/en/stable/validation-rules.html#dependencies. I can see this being useful if user specifies ``sbatch`` as a key in YAML file that is only required if buildtest detects SLURM as the system scheduler. User could specify ``scheduler: slurm``  in ``settings.yml`` or it can be inferred automatically and put in schema.
- Support for ``regex`` https://docs.python-cerberus.org/en/stable/validation-rules.html#regex will come in handy when defining schema
- Custom Rules for schema is an interesting feature https://docs.python-cerberus.org/en/stable/customize.html#custom-rules 

**Cons**

 - Writing JSON schema for YAML file can be a bit challenging but doable


JSON Schema Everywhere
-------------------------------

Seems like this site https://json-schema-everywhere.github.io/yaml is trying to keep track of other JSON tool validators.  

Looking at OpenContainers, i see a JSON schema but not documentation on what JSON rules are they using. Is OpenContainer using some JSON schema syntax as provided by Cerebus.

**Comment by vsoch** [comment]
You can look at the header of their schemas to see they are using json schema. I linked the file above, but here is a direct link to the line https://github.com/opencontainers/image-spec/blob/master/schema/config-schema.json#L3.

You can use the schema without using the Python library which (I think) is what they are doing since most of opencontainers is golang.

**Comment by vsoch** [comment]
Are you good with jsonschema? I think it's the most widely adopted, and that includes the python library: https://github.com/Julian/jsonschema

It does mean we will store our schemas in json, but this is probably okay because the yaml loads to that anyway.

**Comment by shahzebsiddiqui** [comment]
I am going through the docs, got distracted commenting on your issues :)

**Comment by shahzebsiddiqui** [comment]
Okay let's resolve this issue and go with the jsonschema validator and then we can target #5 as the first example.

**Comment by vsoch** [comment]
gotcha
